### ISSUE TITLE
Unable to set date sent when creating new message in folder

### ISSUE THREAD

**Issue by garybentley** [OfficeDev/Office-365-SDK-for-Java#3]
It appears that calling setDateTimeSent (or setDateTimeReceived) on a Message has no effect when creating a new message in a folder.

The new message is created in the folder and is marked as a draft and not sent.  Calling Message.setIsDraft (false) has no effect either.

I used the following test code (shortened):

Message message = new Message ();

java.util.Calendar sentCal = new GregorianCalendar ();
sentCal.setTime (new Date ());
sentCal.setTimeZone (TimeZone.getTimeZone ("GMT"));

message.setDateTimeSent (sentCal);
			
message.setIsDraft (false);

userFetcher.getFolder (folderId).getMessages ().add (message).get (60, TimeUnit.SECONDS);

All the other information in the message is appearing correctly.

**Comment by marcote** [comment]
Hi @garybentley 
Some properties of the Message object are read-only. Also many objects have very specific business rules". For example, you can create and delete folders, but you cannot delete the INBOX folder.  
Creating a message is not the same as sending it, in this case you must call the SEND action in our SDK.

For specific information and behavior of the REST API, please refer to https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations 

Thanks
