### ISSUE TITLE
Gradle wrapper should be added to SCM

### ISSUE THREAD

**Issue by evpaassen** [OfficeDev/Office-365-SDK-for-Java#4]
The [Gradle docs](https://docs.gradle.org/current/userguide/gradle_wrapper.html) say:
> The wrapper is something you should check into version control. By distributing the wrapper with your project, anyone can work with it without needing to install Gradle beforehand.

So I think the lines regarding the Gradle wrapper should be removed from the .gitignore file and the wrapper should be added to the repository.

**Comment by marcote** [comment]
Agree. Will do it shortly.
Thanks

**Comment by marcote** [comment]
I've already added the gradle wrapper files due recent feedback. I just checked it and it's there. Let me know if something is missing reopening the issue.

**Comment by evpaassen** [comment]
Ah. I missed that, sorry. Thanks anyway.
